[package]
name = "osc2midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
midir = "0.9.1"
rosc = "0.9.1"
